### ISSUE TITLE
Token Crash Loop

### ISSUE THREAD

**Issue by qwertynerd97** [qwertynerd97/ao3-reader#1]
If the AO3 reader crashes for whatever reason, the login cookie in the Settings.toml file is replaced by a blank string.  This results in the AO3 reader crashing on every subsequent startup, with the log
```
thread 'main' panicked at crates/core/src/http.rs:97:44:
called `Option::unwrap()` on a `None` value
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'main' panicked at crates/core/src/http.rs:97:44:
called `Option::unwrap()` on a `None` value
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
This appears to be caused by [crates/core/src/http.rs:line 50](https://github.com/momijizukamori/ao3-reader/blob/master/crates/core/src/http.rs#L50), where the login cookie is force unwrapped

**Comment by qwertynerd97** [comment]
This can be fixed by the end user by resetting the Settings.toml file
